
return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "God Damnit Not Again!",
			GENERIC = "I can't lose to that",
			NOBITS = "There isn't even a tiny bit left!",
		},
		STORE =
		{
			GENERIC = "It's full.",
			NOTALLOWED = "That can't go in there.",
		},
	},
	ACTIONFAIL_GENERIC = "Can't do that.",
	ANNOUNCE_ADVENTUREFAIL = "This time you win! Next Time I Win I Will Be Back",
	ANNOUNCE_BEES = "Red terror!",
	ANNOUNCE_BOOMERANG = "I'll catch it!",
	ANNOUNCE_CHARLIE = "What The Heck was that sound?!",
	ANNOUNCE_CHARLIE_ATTACK = "OW! It Hits!",
	ANNOUNCE_COLD = "I hate cold...",
	ANNOUNCE_HOT = "Go away stupid heater!",
	ANNOUNCE_CRAFTING_FAIL = "I'm missing something here...",
	ANNOUNCE_DEERCLOPS = "There is some big guy around",
	ANNOUNCE_DUSK = "Darkness is coming...",
	ANNOUNCE_EAT =
	{
		GENERIC = "Yum!",
		PAINFUL = "Oh It Rusts",
		SPOILED = "You Spoiled Rust",
		STALE = "...",
		INVALID = "No way I'm going to eat THAT!",
	},
	ANNOUNCE_ENTER_DARK = "I can't see!",
	ANNOUNCE_ENTER_LIGHT = "...and there was light!",
	ANNOUNCE_FREEDOM = "I'm free!",
	ANNOUNCE_HIGHRESEARCH = "Who is the best now?",
	ANNOUNCE_HOUNDS = "Come out you chihuahua",
	ANNOUNCE_HUNGRY = "Gimme pizza - now!",
	ANNOUNCE_HUNT_BEAST_NEARBY = "I'll track you down.",
	ANNOUNCE_HUNT_LOST_TRAIL = "Grrr... Next time I'll eat you!",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "Lost the trail. Damn...",
	ANNOUNCE_INV_FULL = "I can't take any more pizza!",
	ANNOUNCE_KNOCKEDOUT = "Ugh, my head!",
	ANNOUNCE_LOWRESEARCH = "I didn't learn much now.",
	ANNOUNCE_MOSQUITOS = "I hate you too, rust bug!",
	ANNOUNCE_NODANGERSLEEP = "How can I sleep right now?!",
	ANNOUNCE_NODAYSLEEP = "Too bright to sleep...",
	ANNOUNCE_NODAYSLEEP_CAVE = "I'm not tired.",
	ANNOUNCE_NOHUNGERSLEEP = "Can't sleep when I'm hungry!",
	ANNOUNCE_NOSLEEPONFIRE = "Sleeping here is not a good idea.",
	ANNOUNCE_NODANGERSIESTA = "It's too dangerous here!",
	ANNOUNCE_NONIGHTSIESTA = "Night is for sleeping not for siesta",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "I don't think I could really relax down here.",
	ANNOUNCE_NOHUNGERSIESTA = "First food. Then siesta!",
	ANNOUNCE_NO_TRAP = "Well that wasn't a challenge.",
	ANNOUNCE_PECKED = "Stop it or I'll bite!",
	ANNOUNCE_QUAKE = "That doesn't sound good.",
	ANNOUNCE_RESEARCH = "I didn't know that before...",
	ANNOUNCE_SHELTER = "Always less rain... thank you tree!",
	ANNOUNCE_THORNS = "Ouch!",
	ANNOUNCE_BURNT = "Hot! Hot! Hot!",
	ANNOUNCE_TORCH_OUT = "Oops! Light's gone!",
	ANNOUNCE_TRAP_WENT_OFF = "Oww!",
	ANNOUNCE_UNIMPLEMENTED = "It's not ready... yet.",
	ANNOUNCE_WORMHOLE = "I'll have nightmares about this.",
	ANNOUNCE_CANFIX = "\nI think I can fix this!",
	ANNOUNCE_ACCOMPLISHMENT = "Accomplished!",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "Watch me! I'm the best!",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "Are you still hungry, plant?",
	ANNOUNCE_TOOL_SLIP = "Wow that is slippery!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "Phew. That was close.",

	ANNOUNCE_DAMP = "Oh, I hate rain",
	ANNOUNCE_WET = "I can smell wet fur... Wait that's me!",
	ANNOUNCE_WETTER = "More and more wet fur...",
	ANNOUNCE_SOAKED = "Now there is even water in my ears...",
	
	BATTLECRY =
	{
		GENERIC = "Banzai!!!",
		PIG = "Don't run... I'll only take a bite!",
		PREY = "I'll crush you!",
		SPIDER = "I'll eat you!",
		SPIDER_WARRIOR = "Begone!",
	},
	COMBAT_QUIT =
	{
		GENERIC = "Victory!",
		PIG = "I'll be back for dinner next time.",
		PREY = "He was lucky!",
		SPIDER = "I wasn't that hungry anyway...",
		SPIDER_WARRIOR = "Why they have to be spiders!?",
	},
	DESCRIBE =
	{
        GLOMMER = "He smells funny...",
        GLOMMERFLOWER = 
        {
        	GENERIC = "It's not an ordinary flower",
        	DEAD = "Bye, flower.",
        },
        GLOMMERWINGS = "I believe, I can flyyy...!",
        GLOMMERFUEL = "Pink... Poo...",
        BELL = "Jingle Bell!",
        STATUEGLOMMER = 
        {	
        	GENERIC = "This doesn't look familiar.",
        	EMPTY = "I didn't do it!",
    	},

		WEBBERSKULL = "I feel like I should bury that.",
		WORMLIGHT = "That's cool.",
		WORM =
		{
		    PLANT = "Nothing awesome.",
		    DIRT = "Just a pile of dirt...",
		    WORM = "It's horrible!",
		},
		MOLE =
		{
			HELD = "You are not going anywhere!",
			UNDERGROUND = "What is under there?",
			ABOVEGROUND = "He is creepy...",
		},
		MOLEHILL = "Reminds me of my home a little.",
		MOLEHAT = "I don't wanna put that on my head.",

		EEL = "Delicious!",
		EEL_COOKED = "What an awesome smell",
		UNAGI = "My own recipe!",
		EYETURRET = "Don't look at me like that!",
		EYETURRET_ITEM = "Is it sleeping or what?",
		MINOTAURHORN = "A horn.",
		MINOTAURCHEST = "My preciousss!",
		THULECITE_PIECES = "Smaller shiny rocks.",
		POND_ALGAE = "Slimy plants.",
		GREENSTAFF = "I like the colour.",
		POTTEDFERN = "A fern. And a pot.",

		THULECITE = "Shiny!",
		ARMORRUINS = "It's oddly light.",
		RUINS_BAT = "It has quite a heft to it.",
		RUINSHAT = "Fit for a king. Or me.",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "All is well.",
		WARN = "Getting pretty magical around here.",
		WAXING = "I think it's becoming more concentrated!",
		STEADY = "It seems to be staying steady.",
		WANING = "Feels like it's receding.",
		DAWN = "The nightmare is almost gone!",
		NOMAGIC = "There's no magic around here.",
		},
		BISHOP_NIGHTMARE = "It's falling apart!",
		ROOK_NIGHTMARE = "Terrifying!",
		KNIGHT_NIGHTMARE = "Not adorable...",
		MINOTAUR = "That thing doesn't look happy.",
		SPIDER_DROPPER = "Let's just go.",
		NIGHTMARELIGHT = "Another weird thing.",
		NIGHTSTICK = "I better not touch it!",
		GREENGEM = "Beautiful.",
		RELIC = "It's an old garbage.",
		RUINS_RUBBLE = "Ruined ruins.",
		MULTITOOL_AXE_PICKAXE = "Might be handy!",
		ORANGESTAFF = "Totally my colour!",
		YELLOWAMULET = "Feels nice.",
		GREENAMULET = "Reminds me of my village.",
		SLURPERPELT = "Piece of wet, stinky fur.",	

		SLURPER = "Wouldn't cuddle him.",
		SLURPER_PELT = "Piece of wet, stinky fur.",
		ARMORSLURPER = "Not really cool.",
		ORANGEAMULET = "Teleportation? Yay!",
		YELLOWSTAFF = "It's warm...",
		YELLOWGEM = "Looks like a yellow candy.",
		ORANGEGEM = "Looks like a candy.",
		TELEBASE = 
		{
			VALID = "Guess it's ready.",
			GEMS = "More purple gems will do it.",
		},
		GEMSOCKET = 
		{
			VALID = "Ready!",
			GEMS = "One more gem...",
		},
		STAFFLIGHT = "I have a bad feeling about this.",
	
        ANCIENT_ALTAR = "An ancient... something.",

        ANCIENT_ALTAR_BROKEN = "It's old and broken.",

        ANCIENT_STATUE = "What a sad face...",

        LICHEN = "How did it grow here?",
		CUTLICHEN = "Maybe it's good, but I don't wanna taste it",

		CAVE_BANANA = "I'm not a monkey to eat that.",
		CAVE_BANANA_COOKED = "Eww!",
		CAVE_BANANA_TREE = "I bet they are poisonous.",
		ROCKY = "Rocky shrimp!",
		
		COMPASS =
		{
			GENERIC="Shows nothing?!",
			N = "North",
			S = "South",
			E = "East",
			W = "West",
			NE = "Northeast",
			SE = "Southeast",
			NW = "Northwest",
			SW = "Southwest",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "I can smell trouble!",
			STEADY = "It seems steady.",
			WANING = "I think it's receding.",
			DAWN = "Nightmare is fading!",
			WARN = "What a funny feeling...",
			CALM = "It's calm now.",
			NOMAGIC = "There's no magic around here.",
		},

		HOUNDSTOOTH="Sharp but mine are sharper!",
		ARMORSNURTLESHELL="Biggie shell.",
		BAT="Flying mouse!",
		BATBAT = "Interesting.",
		BATWING="Can't wait to eat it!",
		BATWING_COOKED="Hot-bat-wings, anyone?",
		BEDROLL_FURRY="Me loves warm...",
		BUNNYMAN="Huge, fat, tasty... I WANT!",
		FLOWER_CAVE="It's glowing.",
		FLOWER_CAVE_DOUBLE="It's glowing.",
		FLOWER_CAVE_TRIPLE="It's glowing.",
		GUANO="Eww! No way!",
		LANTERN="Almost perfect.",
		LIGHTBULB="It smells weird.",
		MANRABBIT_TAIL="I have fluffier tail, but it's nice.",
		MUSHTREE_TALL  ="How did it even grow that much?",
		MUSHTREE_MEDIUM="I know someone who would love it.",
		MUSHTREE_SMALL ="A mushroom? Hehe...",
		RABBITHOUSE=
		{
			GENERIC = "Pathetic.",
			BURNT = "Even more pathetic.",
		},
		SLURTLE="No. Just no.",
		SLURTLE_SHELLPIECES="Puzzle?",
		SLURTLEHAT="I will stand against my fur...",
		SLURTLEHOLE="Slimy doom inside there.",
		SLURTLESLIME="Can't believe I touched it.",
		SNURTLE="He's even more ewww now.",
		SPIDER_HIDER="Dinner time!!",
		SPIDER_SPITTER="Here little spider...",
		SPIDERHOLE="Do I see web there?",
		STALAGMITE="Boring rock.",
		STALAGMITE_FULL="Boring rock.",
		STALAGMITE_LOW="Boring rock.",
		STALAGMITE_MED="Boring rock.",
		STALAGMITE_TALL="Bigger boring rock...",
		STALAGMITE_TALL_FULL="Bigger boring rock...",
		STALAGMITE_TALL_LOW="Bigger boring rock...",
		STALAGMITE_TALL_MED="Bigger boring rock...",

		TURF_CARPETFLOOR = "Piece of dirt.",
		TURF_CHECKERFLOOR = "Piece of dirt.",
		TURF_DIRT = "Piece of dirt.",
		TURF_FOREST = "Piece of dirt.",
		TURF_GRASS = "Piece of dirt.",
		TURF_MARSH = "Piece of dirt.",
		TURF_ROAD = "Piece of dirt.",
		TURF_ROCKY = "Piece of dirt.",
		TURF_SAVANNA = "Piece of dirt.",
		TURF_WOODFLOOR = "Piece of dirt.",

		TURF_CAVE="Piece of dirt.",
		TURF_FUNGUS="Piece of dirt.",
		TURF_SINKHOLE="Piece of dirt.",
		TURF_UNDERROCK="Piece of dirt.",
		TURF_MUD="Piece of dirt.",

		TURF_DECIDUOUS = "Piece of dirt.",
		TURD_SANDY = "Piece of dirt.",
		TURF_BADLANDS = "Piece of dirt.",

		POWCAKE = "I don't think so...",
        CAVE_ENTRANCE = 
        {
            GENERIC="Doesn't look very solid.",
            OPEN = "Reminds me of home in some weird way.",
        },
        CAVE_EXIT = "Let me out of here!",
		MAXWELLPHONOGRAPH = "So that's where these terrible sounds come from.",
		BOOMERANG = "I never liked those!",
		PIGGUARD = "He doesn't look friendly, but sure tasty.",
		ABIGAIL = "Ow cmon, take that bedsheet off.",
		ADVENTURE_PORTAL = "I remember that smell and it's not a good memory.",
		AMULET = "I have a good feeling about this.",
		ANIMAL_TRACK = "Food went that way!",
		ARMORGRASS = "Not really best choice.",
		ARMORMARBLE = "Ugh! Too heavy!",
		ARMORWOOD = "This will work out!",
		ARMOR_SANITY = "It's good, but something feels weird...",
		ASH =
		{
			GENERIC = "All that's left after fire has done its job.",
			REMAINS_GLOMMERFLOWER = "Ow great stupid portal burnt the flower!",
			REMAINS_EYE_BONE = "Nooo! My eye bone is dead",
			REMAINS_THINGIE = "This was once some thing before it got burned...",
		},
		AXE = "It's an axe.",
		BABYBEEFALO = "I... want... eat... that!",
		BACKPACK = "Great! More space for my stuff!",
		BACONEGGS = "I cooked it myself!",
		BANDAGE = "Atleast they are clean.",
		BASALT = "Don't think I can break through.",
		BATBAT = "Interesting.",
		BEARDHAIR = "They smell like... Rabbits?!",
		BEARGER = "What a bear of a badger.",
		BEARGERVEST = "Somehow I felt sleepy.",
		ICEPACK = "Almost-pocket fridge!",
		BEARGER_FUR = "Thick fur.",
		BEDROLL_STRAW = "It sticks like wet grass.",
		BEE =
		{
			GENERIC = "Buzzing evil.",
			HELD = "Watch out!",
		},
		BEEBOX =
		{
			FULLHONEY = "It's full of sticky sweetness.",
			GENERIC = "Bees!",
			NOHONEY = "It's empty.",
			SOMEHONEY = "Hurry up bees!",
			BURNT = "I didn't do it!",
		},
		BEEFALO =
		{
			FOLLOWER = "I don't feel same with him.",
			GENERIC = "I love you too, beefalo!",
			NAKED = "Don't be sad!",
			SLEEPING = "They are snoring way too loud.",
		},
		BEEFALOHAT = "Could make a use of that... maybe.",
		BEEFALOWOOL = "This smell makes me hungry somehow.",
		BEEHAT = "Haha! Perfect for bees",
		BEEHIVE = "Too much buzzing inside.",
		BEEMINE = "It buzzes when I poke it...",
		BEEMINE_MAXWELL = "Mosquito bomb!",
		BERRIES = "There are better things to eat.",
		BERRIES_COOKED = "Even worst now.",
		BERRYBUSH =
		{
			BARREN = "Guess the bush is hungry too",
			WITHERED = "Too hot, even for it.",
			GENERIC = "There are better things to eat.",
			PICKED = "Will they grow back?",
		},
		BIGFOOT = "What the..?! It's huge!",
		BIRDCAGE =
		{
			GENERIC = "Let's catch a bird now!",
			OCCUPIED = "Hi there! Maybe I won't eat you?",
			SLEEPING = "Awwww... Cute.",
		},
		BIRDTRAP = "Come to me birdie!",
		BIRD_EGG = "An egg.",
		BIRD_EGG_COOKED = "Now it stinks!",
		BISHOP = "Back off!",
		BLOWDART_FIRE = "Note to self: don't use it in a forest.",
		BLOWDART_SLEEP = "I better not hurt myself with it.",
		BLOWDART_PIPE = "Useful thing!",
		BLUEAMULET = "Cool as ice! I know who would love it!",
		BLUEGEM = "It feel cold.",
		BLUEPRINT = "I almost understand this!",
		BELL_BLUEPRINT = "Let's see!",
		BLUE_CAP = "What if I get sick after eating it?",
		BLUE_CAP_COOKED = "I still won't eat it",
		BLUE_MUSHROOM =
		{
			GENERIC = "It's a mushroom.",
			INGROUND = "Come out mushroom!",
			PICKED = "I wonder how quick they grow?",
		},
		BOARDS = "Boards.",
		BOAT = "Can I use it to get out from here?",
		BONESHARD = "Bits of bone.",
		BONESTEW = "I cooked it myself!",
		BUGNET = "Let's catch some bugs!",
		BUSHHAT = "Berry-afro.",
		BUTTER = "Butter? Really?",
		BUTTERFLY =
		{
			GENERIC = "Pretty, but it's still a bug.",
			HELD = "Gotcha!",
		},
		BUTTERFLYMUFFIN = "It tastes awful, but it looks nice!",
		BUTTERFLYWINGS = "Poor, little bug...",
		BUZZARD = "Hot wings?",
		CACTUS = 
		{
			GENERIC = "It will hurt my paws...",
			PICKED = "Spiky.",
		},
		CACTUS_MEAT_COOKED = "Almost like meat... ALMOST!",
		CACTUS_MEAT = "No way, too many spikes.",
		CACTUS_FLOWER = "Such a nice flower from such an evil plant.",

		COLDFIRE =
		{
			EMBERS = "I should take care of fire.",
			GENERIC = "Sure beats darkness.",
			HIGH = "Burn!",
			LOW = "Oops it's quite low!",
			NORMAL = "Cool!",
			OUT = "Fire's done.",
		},
		CAMPFIRE =
		{
			EMBERS = "I should take care of fire.",
			GENERIC = "Sure beats darkness.",
			HIGH = "Burn!",
			LOW = "Oops it's quite low!",
			NORMAL = "Sooo warm!",
			OUT = "Fire's done.",
		},
		CANE = "I can run marathon with this!",
		CATCOON = "Hi there... Do I know you?",
		CATCOONDEN = 
		{
			GENERIC = "Something lives there for sure.",
			EMPTY = "...guess it moved out.",
		},
		CATCOONHAT = "Nothing's better than having cat on head...",
		COONTAIL = "Brrr... If someone do that to me?!",
		CARROT = "Yuck. It's all vegetabley.",
		CARROT_COOKED = "Even more yuck",
		CARROT_PLANTED = "Grow little carrots...",
		CARROT_SEEDS = "It's a seed.",
		WATERMELON_SEEDS = "It's a seed.",
		CAVE_FERN = "It's a fern.",
		CHARCOAL = "It smells like burnt wood.",
        CHESSJUNK1 = "A pile of broken chess pieces.",
        CHESSJUNK2 = "Another pile of broken chess pieces.",
        CHESSJUNK3 = "Even more broken chess pieces.",
		CHESTER = "Who is a good boy? You are!",
		CHESTER_EYEBONE =
		{
			GENERIC = "Blinking contest?",
			WAITING = "Ow, it's sleeping.",
		},
		COOKEDMANDRAKE = "I won't eat it even in this state.",
		COOKEDMEAT = "Yum!",
		COOKEDMONSTERMEAT = "Meat is meat!",
		COOKEDSMALLMEAT = "Small but tasty!",
		COOKPOT =
		{
			COOKING_LONG = "Hurry up, cook faster!",
			COOKING_SHORT = "Can't wait to try it!",
			DONE = "Let's eeeaaat!",
			EMPTY = "Aww, empty just when I'm hungry",
			BURNT = "Now it's a cooked-pot.",
		},
		CORN = "Not my flavors.",
		CORN_COOKED = "I better not eat it",
		CORN_SEEDS = "It's a seed.",
		CROW =
		{
			GENERIC = "Bet he tastes great.",
			HELD = "Don't be scared, I won't eat you... yet.",
		},
		CUTGRASS = "Cut grass, might be useful.",
		CUTREEDS = "Cut reeds, I should keep them.",
		CUTSTONE = "That's a nice piece of stone.",
		DEADLYFEAST = "Mmmm what a dish!",
		DEERCLOPS = "I never liked huge, one-eyed, deers!",
		DEERCLOPS_EYEBALL = "Like a huge jellybean.",
		EYEBRELLAHAT =	"That's called having third eye.",
		DEPLETED_GRASS =
		{
			GENERIC = "Still just a grass.",
		},
		DEVTOOL = "It smells funny!",
		DEVTOOL_NODEV = "It's just too heavy!",
		DIRTPILE = "Is it a pile of dirt?",
		DIVININGROD =
		{
			COLD = "Huh? I hear some signal.",
			GENERIC = "Another human-invention?",
			HOT = "My ears burn! Stop it!",
			WARM = "Guess that means I'm getting closer.",
			WARMER = "No it's really close!",
		},
		DIVININGRODBASE =
		{
			GENERIC = "Whatever is it...",
			READY = "It seems to be ready.",
			UNLOCKED = "It works!",
		},
		DIVININGRODSTART = "That rod looks useful!",
		DRAGONFLY = "Giant bug!",
		ARMORDRAGONFLY = "Hot mail!",
		DRAGON_SCALES = "Ouch! They are hot!",
		DRAGONFLYCHEST = "That's nice thing!",
		LAVASPIT = 
		{
			HOT = "Hot!",
			COOL = "Not that hot, eh?",
		},
		DRAGONFRUIT = "Tricky fruit.",
		DRAGONFRUIT_COOKED = "Still too weird to eat.",
		DRAGONFRUIT_SEEDS = "It's a seed.",
		DRAGONPIE = "I better not eat it...",
		DRUMSTICK = "Yum! Gobble sticks!",
		DRUMSTICK_COOKED = "Now it's even tastier.",
		DUG_BERRYBUSH = "I should plant this.",
		DUG_GRASS = "I should plant this.",
		DUG_MARSH_BUSH = "I should plant this.",
		DUG_SAPLING = "I should plant this.",
		DURIAN = "It... stinks!",
		DURIAN_COOKED = "It stinks more now!",
		DURIAN_SEEDS = "It's a seed.",
		EARMUFFSHAT = "Good for my ears, but my belly prefers to eat them!",
		EGGPLANT = "I like the look of it, but thats it.",
		EGGPLANT_COOKED = "Doesn't look nice anymore.",
		EGGPLANT_SEEDS = "It's a seed.",
		DECIDUOUSTREE = 
		{
			BURNING = "Oops!",
			BURNT = "Aw poor tree!",
			CHOPPED = "Sorry tree - I had to do it.",
			POISON = "What do YOU want?!",
			GENERIC = "Trees almost like in my village!",
		},
		ACORN = 
		{
		    GENERIC = "What's inside?",
		    PLANTED = "Grow little tree!",
		},
		ACORN_COOKED = "Eat it? Naaa...",
		BIRCHNUTDRAKE = "Don't me mad.",
		EVERGREEN =
		{
			BURNING = "Oops!",
			BURNT = "Aw poor tree!",
			CHOPPED = "Sorry tree - I had to do it.",
			GENERIC = "It's always green.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "Oops!",
			BURNT = "Aw poor tree!",
			CHOPPED = "Sorry tree - I had to do it.",
			GENERIC = "Aw, where did you loose your cones?",
		},
		EYEPLANT = "Quit staring at me!",
		FARMPLOT =
		{
			GENERIC = "Think I should plant some crops.",
			GROWING = "Grow, grow!",
			NEEDSFERTILIZER = "Hungry little plant?",
			BURNT = "This won't grow for sure.",
		},
		FEATHERHAT = "It's itching my nose!",
		FEATHER_CROW = "A crow feather.",
		FEATHER_ROBIN = "A redbird feather.",
		FEATHER_ROBIN_WINTER = "A snowbird feather.",
		FEM_PUPPET = "She's trapped!",
		FIREFLIES =
		{
			GENERIC = "I have a need of chasing them!",
			HELD = "Will I glow too, if I eat them?",
		},
		FIREHOUND = "Let's call you Sparky!",
		FIREPIT =
		{
			EMBERS = "I should take care of fire!",
			GENERIC = "It beats the darkness.",
			HIGH = "Oops, a bit too big.",
			LOW = "Fire is almost gone.",
			NORMAL = "Rrrr, so nice.",
			OUT = "Now I need to start it up again.",
		},
		COLDFIREPIT =
		{
			EMBERS = "I should take care of fire!",
			GENERIC = "It beats the darkness.",
			HIGH = "Oops, a bit too big.",
			LOW = "Fire is almost gone.",
			NORMAL = "Rrrr, so nice.",
			OUT = "Now I need to start it up again.",
		},
		FIRESTAFF = "Better use it carefully.",
		FIRESUPPRESSOR = 
		{	
			ON = "Fling on!",
			OFF = "All quiet on the flinging front.",
			LOWFUEL = "The fuel tank is getting a bit low.",
		},

		FISH = "I love sushi!",
		FISHINGROD = "Human-fishing tool?",
		FISHSTICKS = "I cooked it myself!",
		FISHTACOS = "I cooked it myself!",
		FISH_COOKED = "Purrrfecto.",
		FLINT = "Sharp rock.",
		FLOWER = "Pretty but too much of smell.",
		FLOWERHAT = "Pretty.",
		FLOWER_EVIL = "Stinks like evil!",
		FOLIAGE = "Some leafy greens.",
		FOOTBALLHAT = "My ears don't like it.",
		FROG =
		{
			DEAD = "It's dinner time!",
			GENERIC = "Little froggy.",
			SLEEPING = "Aww, look at him sleep!",
		},
		FROGGLEBUNWICH = "I cooked it myself!",
		FROGLEGS = "Always wanted taste them.",
		FROGLEGS_COOKED = "A bit... Soggy.",
		FRUITMEDLEY = "I cooked it myself!",
		GEARS = "Pile of metal rubbish.",
		GHOST = "Poor spirit trapped in this world.",
		GOLDENAXE = "Shiny axe.",
		GOLDENPICKAXE = "Shiny pickaxe?",
		GOLDENPITCHFORK = "Waste of gold...",
		GOLDENSHOVEL = "Digging is pleasure with this.",
		GOLDNUGGET = "I can't eat it, but it sure is shiny.",
		GRASS =
		{
			BARREN = "It needs poop.",
			WITHERED = "It's too hot for it to grow.",
			BURNING = "Burning in no time!",
			GENERIC = "It's a tuft of grass.",
			PICKED = "It's picked already.",
		},
		GREEN_CAP = "I better not eat that.",
		GREEN_CAP_COOKED = "It's different now,",
		GREEN_MUSHROOM =
		{
			GENERIC = "It's a mushroom.",
			INGROUND = "Wake up, mushroom!",
			PICKED = "Will it grow back?",
		},
		GUNPOWDER = "Another human-invention.",
		HAMBAT = "Food fight?",
		HAMMER = "Let's rock and destroy!",
		HEALINGSALVE = "Better to make more of them. Just in case.",
		HEATROCK =
		{
			FROZEN = "It's freezing cold.",
			COLD = "It's a cold stone.",
			GENERIC = "Think I can change it's temperature.",
			WARM = "So warm I wanna cuddle it!",
			HOT = "Nice and hot for cold winter evenings!",
		},
		HOME = "Anyone at home?",
		HOMESIGN = 
		{
			GENERIC = "You are here... That means where?",
			BURNT = "Not a big lost.",
		},
		HONEY = "It will make my fur sticky!",
		HONEYCOMB = "Parts of bee-house.",
		HONEYHAM = "I cooked it myself!",
		HONEYNUGGETS = "I cooked it myself!",
		HORN = "Seems like I can play it.",
		HOUND = "You are not that evil really, do you?",
		HOUNDBONE = "I would take a bite too...",
		HOUNDMOUND = "Hounds may like this.",
		ICEBOX = "Winter in a box!",
		ICEHAT = "Cool.",
		ICEHOUND = "Why beeing so cold hearted?",
		INSANITYROCK =
		{
			ACTIVE = "THAT'S INSANE!",
			INACTIVE = "I don't feel good just standing by them.",
		},
		JAMMYPRESERVES = "I cooked it myself!",
		KABOBS = "I cooked it myself!",
		KILLERBEE =
		{
			GENERIC = "Mad bee!",
			HELD = "Still dangerous.",
		},
		KNIGHT = "Wanna play?",
		KOALEFANT_SUMMER = "Deliciousss!",
		KOALEFANT_WINTER = "I will only take a bite... ok?",
		KRAMPUS = "Leave my things, you thief!",
		KRAMPUS_SACK = "Eww, it stinks like Krapus!",
		LEIF = "That's a big one!",
		LEIF_SPARSE = "That's a big one!",
		LIGHTNING_ROD =
		{
			CHARGED = "Thunder in a metal stick?",
			GENERIC = "Thunders likes it for some reason.",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "Energetic meal!",
			CHARGED = "Charged!",
		},
		LIGHTNINGGOATHORN = "Almost like lightning rod.",
		GOATMILK = "It smells funny.",
		LITTLE_WALRUS = "Deadly even if small.",
		LIVINGLOG = "Is it alive?",
		LOCKEDWES = "I should try saving him.",
		LOG =
		{
			BURNING = "They burn so fast...",
			GENERIC = "Nice piece of wood.",
		},
		LUREPLANT = "Smell makes me come closer.",
		LUREPLANTBULB = "Should I plant my own?",
		MALE_PUPPET = "He's trapped!",
		MANDRAKE =
		{
			DEAD = "I can feel some of it's magic.",
			GENERIC = "I've heard legends about those plants.",
			PICKED = "It's creepy...",
		},
		MANDRAKESOUP = "I cooked it myself!",
		MANDRAKE_COOKED = "Not so creepy anymore huh?",
		MARBLE = "Nice!",
		MARBLEPILLAR = "I could use it somehow!",
		MARBLETREE = "Axe is too weak to deal with it.",
		MARSH_BUSH =
		{
			BURNING = "Burn, evil bush!",
			GENERIC = "Touching it might hurt.",
			PICKED = "Ouch!",
		},
		MARSH_PLANT = "A plant.",
		MARSH_TREE =
		{
			BURNING = "Spiky and hot.",
			BURNT = "Spiky and burnt.",
			CHOPPED = "Ha! No so spiky anymore!",
			GENERIC = "I better be careful with them.",
		},
		MAXWELL = "Grrr! He trapped me here!",
		MAXWELLHEAD = "He's definitely not pretty at all.",
		MAXWELLLIGHT = "How can they work...",
		MAXWELLLOCK = "It needs some sort of key.",
		MAXWELLTHRONE = "This guy always had a big ego.",
		MEAT = "I love it!",
		MEATBALLS = "I cooked it myself!",
		MEATRACK =
		{
			DONE = "My favourite!",
			DRYING = "Hurry up, meat!",
			DRYINGINRAIN = "Stupid rain, makes it dry longer.",
			GENERIC = "I will dry some meat when I can.",
			BURNT = "Ooops now it's really DRY.",
		},
		MEAT_DRIED = "Tasty jerky.",
		MERM = "Smells like an old, wet boot!",
		MERMHEAD = 
		{
			GENERIC = "This stink burns my nose!",
			BURNT = "It's still ugly.",
		},
		MERMHOUSE = 
		{
			GENERIC = "I wouldn't live here.",
			BURNT = "Not a big lost.",
		},
		MINERHAT = "Shining hat? Handy!",
		MONKEY = "Want a banana?",
		MONKEYBARREL = "Did that just move?",
		MONSTERLASAGNA = "I cooked it myself!",
		FLOWERSALAD = "Rabbits' food.",
        ICECREAM = "Cold!",
        WATERMELONICLE = "Ice-melon.",
        TRAILMIX = "Bag of fruits and nuts...",
        HOTCHILI = "Now that's really hot.",
        GUACAMOLE = "Smells wonderful!",
		MONSTERMEAT = "Meat is meat!",
		MONSTERMEAT_DRIED = "Strange smell, but great taste.",
		MOOSE = "What on the Earth is that?!",
		MOOSEEGG = "There is something inside...",
		MOSSLING = "It's even cute.",
		FEATHERFAN = "Phew... Lowers the heat.",
		GOOSE_FEATHER = "It tickles!",
		STAFF_TORNADO = "Stick of the wind.",
		MOSQUITO =
		{
			GENERIC = "Get away from me!",
			HELD = "Give.Me.Back.My.Blood!",
		},
		MOSQUITOSACK = "Eww.. just ewww..",
		MOUND =
		{
			DUG = "Diggi, diggi hole!",
			GENERIC = "I bet there's all sorts of good stuff down there!",
		},
		NIGHTLIGHT = "Spooky.",
		NIGHTMAREFUEL = "Insane thing!",
		NIGHTSWORD = "Amazing but feels bad using it.",
		NITRE = "Cold rock.",
		ONEMANBAND = "This will hurt my ears...",
		PANDORASCHEST = "I remember there were similar in our Village.",
		PANFLUTE = "I can play for my forest friends!",
		PAPYRUS = "Sheet of paper.",
		PENGUIN = "Never ate frozen bird yet.",
		PERD = "Don't run away!",
		PEROGIES = "I cooked it myself!",
		PETALS = "Poor flower.",
		PETALS_EVIL = "They smell like pure evil...",
		PICKAXE = "I can break rocks with it.",
		PIGGYBACK = "It's heavy... like pig's butt.",
		PIGHEAD = 
		{	
			GENERIC = "Piggie made someone mad...",
			BURNT = "Crunchy!",
		},
		PIGHOUSE =
		{
			FULL = "Little pig, let me come in..",
			GENERIC = "Funny house, but doesn't look solid.",
			LIGHTSOUT = "I'll huff, and I'll puff, and I'll blow your house in.",
			BURNT = "Warned him.",
		},
		PIGKING = "Fatty!",
		PIGMAN =
		{
			DEAD = "Ooops poor piggie...",
			FOLLOWER = "Food is following me, great!",
			GENERIC = "Pink lunch boxes, on short legs.",
			GUARD = "He looks serious.",
			WEREPIG = "Aaah! Not cool anymore!",
		},
		PIGSKIN = "Pig's BUTT!",
		PIGTENT = "Ham-tent.",
		PIGTORCH = "Pig's tribal art.",
		PINECONE = 
		{
		    GENERIC = "Little tree!",
		    PLANTED = "Grow little tree!",
		},
		PITCHFORK = "I can move turf.",
		PLANTMEAT = "Ok is it meat or plant then?",
		PLANTMEAT_COOKED = "Smells more like meat now.",
		PLANT_NORMAL =
		{
			GENERIC = "Plant.",
			GROWING = "It's growing slow.",
			READY = "Harvesting time!",
			WITHERED = "Great, sun killed it.",
		},
		POMEGRANATE = "I don't like the looks of it!",
		POMEGRANATE_COOKED = "Still doesn't look tasty enough.",
		POMEGRANATE_SEEDS = "It's a seed.",
		POND = "Shallow pond.",
		POOP = "That's a lot of poop!",
		FERTILIZER = "That's even more of poop!",
		PUMPKIN = "What can I make out of it?",
		PUMPKINCOOKIE = "I cooked it myself!",
		PUMPKIN_COOKED = "Cooked or not it's not my type.",
		PUMPKIN_LANTERN = "Creepy!",
		PUMPKIN_SEEDS = "It's a seed.",
		PURPLEAMULET = "It has weird energy.",
		PURPLEGEM = "Mysterious, magical gem.",
		RABBIT =
		{
			GENERIC = "Little carrot-eater.",
			HELD = "You are cute and tasty for sure.",
		},
		RABBITHOLE = 
		{
			GENERIC = "To small to jump in.",
			SPRING = "Nobody at home?",
		},
		RAINOMETER = 
		{	
			GENERIC = "Human-invention... But it can be useful.",
			BURNT = "Guess it's time is up.",
		},
		RAINCOAT = "No more wet fur! I love this!",
		RAINHAT = "I don't like hats, but this one is perfect!",
		RATATOUILLE = "Veggies? No thank you.",
		RAZOR = "Sharp rock on a stick.",
		REDGEM = "Hot gem.",
		RED_CAP = "It smells funny.",
		RED_CAP_COOKED = "It's different now...",
		RED_MUSHROOM =
		{
			GENERIC = "It's a mushroom.",
			INGROUND = "Wake up mushroom!",
			PICKED = "Will it come back?",
		},
		REEDS =
		{
			BURNING = "They are burning!",
			GENERIC = "Usual reeds.",
			PICKED = "I picked them.",
		},
        RELIC = 
        {
            GENERIC = "Ancient... something.",
            BROKEN = "Broken ancient something.",
        },
        RUINS_RUBBLE = "I think it can be fixed.",
        RUBBLE = "Almost like rock-puzzle.",
		RESEARCHLAB = 
		{	
			GENERIC = "Seems like it can break things!",
			BURNT = "It's not useful anymore",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "It's similar to the last one!",
			BURNT = "Now it's only pile of ash.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "What did I just made?",
			BURNT = "It's nothing now.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "How could I describe it?",
			BURNT = "No more problem.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "Horrific piece of art!",
			BURNT = "At least I don't need to look at it anymore.",
		},
		RESURRECTIONSTONE = "This stone has some kind of energy...",
		ROBIN =
		{
			GENERIC = "Hi birdy!",
			HELD = "I won't eat you... yet.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "Aren't you cold?!",
			HELD = "So pretty and so tasty.",
		},
		ROBOT_PUPPET = "It's trapped!",
		ROCK_LIGHT =
		{
			GENERIC = "A crusted over lava pit.",
			OUT = "Looks fragile.",
			LOW = "The lava's crusting over.",
			NORMAL = "Nice and comfy.",
		},
		ROCK = "Too big for a souvenir!",
		ROCK_ICE = 
		{
			GENERIC = "Is that a glacier?",
			MELTED = "Maybe it will freeze again?",
		},
		ROCK_ICE_MELTED = "Maybe it will freeze again?",
		ICE = "Cold!!!",
		ROCKS = "I can make something of these.",
        ROOK = "Let's play!",
		ROPE = "Short rope.",
		ROTTENEGG = "What a horrible stink!",
		SANITYROCK =
		{
			ACTIVE = "I swear I saw it moving!",
			INACTIVE = "Wasn't that bigger before?",
		},
		SAPLING =
		{
			BURNING = "Poor baby tree!",
			WITHERED = "It's too dry.",
			GENERIC = "It's a small tree!",
			PICKED = "It's picked.",
		},
		SEEDS = "Such small seed, such big mystery.",
		SEEDS_COOKED = "Now they are useless to me.",
		SEWING_KIT = "Not my story, really!",
		SHOVEL = "Diggi, diggi hole!",
		SILK = "It's so... silky.",
		SKELETON = "I won't end up like that!",
		SKELETON_PLAYER = "I won't end up like... Nevermind.",
		SKULLCHEST = "What can go wrong if I open it?",
		SMALLBIRD =
		{
			GENERIC = "Hi little one!",
			HUNGRY = "Aww, are you hungry?",
			STARVING = "I better feed you!",
		},
		SMALLMEAT = "A tiny piece of meat.",
		SMALLMEAT_DRIED = "A small jerky.",
		SPEAR = "That's a stick with a rock on it.",
		SPIDER =
		{
			DEAD = "Is it dead yet?",
			GENERIC = "How can it walk on so many legs?",
			SLEEPING = "Hush little spider, don't bite a thing!",
		},
		SPIDERDEN = "Ewwww!",
		SPIDEREGGSACK = "Nasty and awful.",
		SPIDERGLAND = "Is that a spider butt?",
		SPIDERHAT = "Smells like she never brushed her teeth.",
		SPIDERQUEEN = "Ahh! That's horrific!",
		SPIDER_WARRIOR =
		{
			DEAD = "Phew!",
			GENERIC = "Those are even worse!",
			SLEEPING = "Just don't wake up when I'm near!",
		},
		SPOILED_FOOD = "It's totally spoiled now.",
		STATUEHARP = "Did he loose his head here as well?",
		STATUEMAXWELL = "Ugly almost as in real.",
		STINGER = "Sharp!",
		STRAWHAT = "Country style!",
		STUFFEDEGGPLANT = "I cooked it myself!",
		SUNKBOAT = "Nobody will use it anymore.",
		SWEATERVEST = "It's some kind of vest.",
		REFLECTIVEVEST = "Let's fight the sun!",
		HAWAIIANSHIRT = "Aloha!",
		TAFFY = "Way too sweet.",
		TALLBIRD = "How's the weather up there?",
		TALLBIRDEGG = "Will it hatch?",
		TALLBIRDEGG_COOKED = "Delicioussss!",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "I think it's too cold for it!",
			GENERIC = "Whatever is inside, it's going to come out.",
			HOT = "Ah! It's boiling!",
			LONG = "I need a lot of patience now.",
			SHORT = "Just a little bit more.",
		},
		TALLBIRDNEST =
		{
			GENERIC = "What a big egg!",
			PICKED = "The nest is empty.",
		},
		TEENBIRD =
		{
			GENERIC = "They grow so fast.",
			HUNGRY = "Hungry?",
			STARVING = "Quit giving me that look!",
		},
		TELEBASE =
		{
			VALID = "Ready to go!",
			GEMS = "I should find more gems!",
		},
		GEMSOCKET = 
		{
			VALID = "Seems ready.",
			GEMS = "Still it needs a gem.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "So can I get out of here with this?",
			GENERIC = "It looks like some kind of portal!",
			LOCKED = "Something is still missing here.",
			PARTIAL = "It's almost like puzzle!",
		},
		TELEPORTATO_BOX = "Box made of wood? Can't open it!",
		TELEPORTATO_CRANK = "This is part of some machine...",
		TELEPORTATO_POTATO = "Doesn't it look like his ugly face?",
		TELEPORTATO_RING = "My precioussss!",
		TELESTAFF = "Lead the way, weird stick!",
		TENT = 
		{
			GENERIC = "Cozy place to sleep.",
			BURNT = "It was such a nice tent.",
		},
		SIESTAHUT = 
		{
			GENERIC = "Awesome place for the hot afternoons.",
			BURNT = "No more precious shadow, awww...",
		},
		TENTACLE = "That's crazy and spiky!",
		TENTACLESPIKE = "Slimy weapon...",
		TENTACLESPOTS = "Soft, slimy... and awful.",
		TENTACLE_PILLAR = "Weird looking pole.",
		TENTACLE_PILLAR_ARM = "Arms?! You must be kidding me!",
		TENTACLE_GARDEN = "Another one?",
		TOPHAT = "What a classy hat!",
		TORCH = "Little light in the darkness.",
		TRANSISTOR = "It's electric... something.",
		TRAP = "Let's catch some food!",
		TRAP_TEETH = "Vicious surprise for someone...",
		TRAP_TEETH_MAXWELL = "I better not step on that!",
		TREASURECHEST = 
		{
			GENERIC = "It's my trunk and my stuff in it!",
			BURNT = "It's more than empty now.",
		},
		TREASURECHEST_TRAP = "It smells... different.",
		TREECLUMP = "They grow so close to each other, that I can't pass!",
		TRINKET_1 = "They are all melted together.",
		TRINKET_10 = "I hope I get out of here before I need these.",
		TRINKET_11 = "He whispers beautiful lies to me.",
		TRINKET_12 = "I'm not sure what I should do with a dessicated tentacle.",
		TRINKET_2 = "It's just a cheap replica.",
		TRINKET_3 = "The knot is stuck. Forever.",
		TRINKET_4 = "It must be some kind of religious artifact.",
		TRINKET_5 = "Sadly, it's too small for me to escape on.",
		TRINKET_6 = "Their electricity carrying days are over.",
		TRINKET_7 = "I have no time for fun and games!",
		TRINKET_8 = "Great. All of my tub stopping needs are met.",
		TRINKET_9 = "I'm more of a zipper person, myself.",
		TRUNKVEST_SUMMER = "I don't like vests on my fur but... I might use it.",
		TRUNKVEST_WINTER = "So uncomfortable with my fur but it's warm!",
		TRUNK_COOKED = "I always wanted to try this.",
		TRUNK_SUMMER = "Those can be obtain in the summer.",
		TRUNK_WINTER = "Trunk with thick hair on it.",
		TUMBLEWEED = "It's almost like unwrapping presents.",
		TURF_CARPETFLOOR = "Nice piece of floor.",
		TURF_CHECKERFLOOR = "Wanna play chess on it?",
		TURF_DIRT = "A chunk of ground.",
		TURF_FOREST = "A chunk of ground.",
		TURF_GRASS = "A chunk of ground.",
		TURF_MARSH = "A chunk of ground.",
		TURF_ROAD = "Cobble-floor.",
		TURF_ROCKY = "A chunk of ground.",
		TURF_SAVANNA = "A chunk of ground.",
		TURF_WOODFLOOR = "Floorboards.",
		TURKEYDINNER = "Yummy!",
		TWIGS = "Those are small twigs.",
		UMBRELLA = "That's the option for keeping my fur dry!",
		GRASS_UMBRELLA = "It's not perfect, but better than nothing.",
		UNIMPLEMENTED = "It looks unfinished! I wouldn't touch it.",
		WAFFLES = "I cooked them... But I don't adore them.",
		WALL_HAY = 
		{	
			GENERIC = "Very poor wall but still a wall.",
			BURNT = "Now it's even more poor...",
		},
		WALL_HAY_ITEM = "That's bad idea.",
		WALL_STONE = "Nice wall made of stone.",
		WALL_STONE_ITEM = "I feel safe.",
		WALL_RUINS = "It looks like an ancient wall.",
		WALL_RUINS_ITEM = "Mysterious piece of history.",
		WALL_WOOD = 
		{
			GENERIC = "I like the sharp endings!",
			BURNT = "Now it's totally burnt!",
		},
		WALL_WOOD_ITEM = "Pickets!",
		WALRUS = "Fat, big and stupid, but still dangerous.",
		WALRUSHAT = "It stinks like walrus!",
		WALRUS_CAMP =
		{
			EMPTY = "I can smell walrus... But it was here long time ago.",
			GENERIC = "Well it even looks quite comfortable.",
		},
		WALRUS_TUSK = "This can be used for sure!",
		WARG = "C'mon why beeing so mad?!",
		WASPHIVE = "It's a home of crazy bee!",
		WATERMELON = "Sticky sweet.",
		WATERMELON_COOKED = "Still sticky...",
		WATERMELONHAT = "My poor fur will be all sticky if I wear that!",
		WETGOOP = "I never said I was a top chef!",
		WINTERHAT = "I might keep this for winter.",
		WINTEROMETER = 
		{
			GENERIC = "Human-invention... Seems it's measuring something.",
			BURNT = "Well, it's not working anymore.",
		},
		WORMHOLE =
		{
			GENERIC = "I have an urgent need to touch it!",
			OPEN = "It seems endless!",
		},
		WORMHOLE_LIMITED = "Ah! What happened to it? Doesn't look good.",
		ACCOMPLISHMENT_SHRINE = "Maybe using it will please the Ancient Spirits!",        
		LIVINGTREE = "It has some kind of energy!",
		ICESTAFF = "I feel cold just looking at it.",
	},
	DESCRIBE_GENERIC = "It's... something.",
	DESCRIBE_TOODARK = "I can't see!",
	DESCRIBE_SMOLDERING = "It will catch fire soon!",
	EAT_FOOD =
	{
		TALLBIRDEGG_CRACKED = "Nutricious, tasty egg!",
	},
}
